[IV-21-22]  Objetivo 4
JAntonioVR/IV-2021-2022 pull request #31
Opened 2021-11-07 20:16 UTC by JAntonioVR

Con este PR completo las tareas del objetivo 4. En concreto:
* Se han creado funciones de test para los atributos de la clase `Resenia` (#28).
* Se han creado métodos en la clase `ConjuntoResenia` para inicializar las estructuras de datos a partir de un fichero de texto (#23, #24, #25, #26).
* Se han implementado test para los métodos recientemente comentados (#27, #28)
* Se han incluido código para automatizar la ejecución de estos test. Con tan solo ejecutar `invoke test` se lanzan los test (#29 ).
* Se ha incluido y modificado la documentación de todo el código y el README principal (#30).

2021-11-07 20:28 UTC, JAntonioVR commented
Listo para revisión @JJ

2021-11-09 12:10 UTC, JJ requested changes
No has justificado ni mencionado qué test runner y biblioteca de aserciones has elegido.

2021-11-09 12:10 UTC, JJ commented on pyproject.toml
> +pandas = "^1.3.4"
No deberíais tener que usar ninguna biblioteca externa en esta fase.

2021-11-09 12:10 UTC, JJ commented on review_set/conjunto_resenias.py
> +        return self.resenias[index]
El usuario qué va a saber, ¿el local o la reseña? Si lo que saben es el local, ¿por qué pones una búsqueda ineficiente para ese y una eficiente para este? (O(N) v. O(1)). ¿Quién quiere buscar por índice, además? ¿Qué HU/user journey lo justifica?

2021-11-09 12:10 UTC, JJ commented on review_set/conjunto_resenias.py
> +        self.resenias = []
Uf, te cargas todos los datos que hubiera. ¿El constructor sabe esto?

2021-11-09 12:10 UTC, JJ commented on review_set/conjunto_resenias.py
> +            assert(spamreader != None)
??? Las aserciones deben ir al test, aquí debes capturar y lanzar excepciones.

2021-11-09 12:10 UTC, JJ commented on tasks.py
>  sys.path.append('./test')
???

2021-11-09 12:10 UTC, JJ commented on tasks.py
> +    test_constructor_conjunto_resenias()
Los tests tienen que ir en su propio fichero, y lanzarse desde el "test runner"

2021-11-11 16:59 UTC, JAntonioVR commented
Listo para revisión @JJ

2021-11-11 19:48 UTC, JJ approved these changes
:+1:

2021-11-11 19:48 UTC, JJ commented on review_set/conjunto_resenias.py
> +        return self.resenias[index]
Ping? Si no, ya para el objetivo siguiente.

2021-11-12 11:37 UTC, JAntonioVR commented
:clap: :clap: :smile:

2021-11-12 11:37 UTC, merged