[IV-21-22] Objetivo 5
JAntonioVR/IV-2021-2022 pull request #35
Opened 2021-11-23 18:23 UTC by JAntonioVR

Con este pull request completo las tareas correspondientes al objetivo 5.

* Se ha diseñado y construido un contenedor de `Docker` con todo lo necesario para ejecutar los test implementados en el [objetivo anterior](https://github.com/JAntonioVR/IV-2021-2022/pull/31) (#33).
* Una vez construido el contenedor, se ha sincronizado el mismo con `Docker Hub` y se ha automatizado su construcción y subida en cada `push` mediante un action de github (#34).
* Se ha actualizado la documentación hasta el punto de desarrollo actual, reabriendo el issue #30 y permaneciendo así hasta la finalización de toda la documentación.
* Uso del gestor de tareas para la ejecución de los test utilizando el gestor de tareas mediante una nueva tarea (#29).

2021-11-23 18:47 UTC, JAntonioVR commented
Listo para revisión @JJ

2021-11-26 09:25 UTC, JJ requested changes
La justificación del contenedor elegido no es suficiente, y eres como el 4º o el 5º que pone Python 3.8 sin una justificación clara. El resto son temas menores, pero te agradecería que lo hicieras de todas formas.

2021-11-26 09:25 UTC, JJ commented on Dockerfile
> +FROM python:3.8
Esto lo vas a tener que justificar *muy* bien...

2021-11-26 09:25 UTC, JJ commented on Dockerfile
> +WORKDIR /home/iv_app
Si esto lo pones justo arriba puedes usar COPY a .

2021-11-26 09:25 UTC, JJ commented on Dockerfile
> +&&  poetry config virtualenvs.create false \
También vas a tener que justificarlo *muy* bien y/o comprobar si *realmente* hace falta.

2021-11-26 09:25 UTC, JJ commented on Dockerfile
> +&&  pip install invoke \
Si ya tienes poetry instalado, porqué no lo usas?

2021-11-26 09:25 UTC, JJ commented on README.md
> +### Virtualización
Realmente, no es virtualización... Ya lo expliqué en clase.

2021-11-26 09:25 UTC, JJ commented on README.md
> +* Se ha utilizado como contenedor base la [imagen oficial de `Python`](https://hub.docker.com/_/python), en su versión 3.8. Tras comparar otras opciones, la conclusión que saqué es que, al menos en e
¿Cómo las comparaste? ¿Con qué criterios? ¿Dónde está el resultado de esa comparación? ¿No puedes usar un contenedor base e instalar tú mismo Python con pyenv o como sea?

2021-11-26 11:40 UTC, JAntonioVR commented on Dockerfile
> +&&  poetry config virtualenvs.create false \
Efectivamente no era necesario, lo he eliminado

2021-11-28 12:59 UTC, JAntonioVR commented
Listo para revisión @JJ (solo el objetivo 5)

2021-11-28 18:52 UTC, JJ commented
Tienes un error en CircleCI. Mientras no pase los tests no se puede aprobar.

2021-12-01 11:00 UTC, JAntonioVR commented
Listo para revisión @JJ

2021-12-07 19:20 UTC, JJ approved these changes
Está mal justificado, pero al menos se ha intentado justificar. Te agradecería que lo corrigieras para el siguiente objetivo.

2021-12-07 19:20 UTC, JJ commented on .circleci/config.yml
> +      # - checkout
¿Por qué dejas todo esto?

2021-12-07 19:20 UTC, JJ commented on Dockerfile
> +WORKDIR /home/iv_app
Esto ya os lo he dicho varias veces. Estás copiando a un directorio que se va a pisar cuando se monte. Usad cualquier otro directorio para hacer las instalaciones.

2021-12-07 19:20 UTC, JJ commented on README.md
> +Se ha utilizado como contenedor base la [imagen oficial de `Python`](https://hub.docker.com/_/python), en su versión 3.8-slim.
Una vez más, no se comunica la decisión, se justifica.

2021-12-07 19:20 UTC, JJ commented on README.md
> +* Se necesita un contenedor con soporte para ejecutar código de python y una herramienta para ejecutar el gestor de dependencias. En nuestro caso esta herramienta es `pip`.
Los requisitos deben ir antes de la decisión.

2021-12-07 19:20 UTC, JJ commented on README.md
> +En `dockerhub` hay muchas posibilidades, pero tomaremos la decisión de centrarnos en las imágenes oficiales, por ser considerado buena práctica al ser actualizadas regularmente y más seguras que las
¿Por qué las oficiales del lenguajes y no las oficiales de la distribución que vayas a usar?

2021-12-07 19:20 UTC, JJ commented on README.md
> +Como vemos, el tiempo de ejecución de los tests y el tamaño de la imagen no es significativo, por lo que nos centraremos en el tiempo de construcción y subida. Las versiones construidas utilizando ve
... que es menos significativo todavía, ya que sólo se hace una vez.

2021-12-09 09:10 UTC, merged