[IV-21-22] Objetivo 6
JAntonioVR/IV-2021-2022 pull request #38
Opened 2021-12-12 16:35 UTC by JAntonioVR

Con este PR completo las tareas correspondientes al objetivo 6, concretamente:

* Se ha parametrizado la construcción del contenedor para poder usar distintos contenedores base (#33).
* Se ha integrado esta parametrización para que en cada push se construyan y suban a DockerHub distintas imágenes (#34).
* Se ha configurado un sistema de integración continua que testea el código con las distintas versiones (#36).
* Se ha configurado otro sistema de integración continua que sólo testea el código con la versión por defecto (#37).

---

* [X]  ¿Se han configurado varios sistemas de integración continua?
* [X]  ¿Se ha configurado correctamente el *Checks API* en los sistemas en los que
   sea necesario para que aparezca correctamente en GitHub (y se pueda comprobar
   desde los tests)?
* [X]  ¿Uno de los sistemas configurados permite comprobar cuales son las versiones
   del lenguaje con las que funciona correctamente nuestra aplicación?
* [X]  ¿Se escogen de forma adecuada las versiones del lenguaje que se testean,
   tanto en el sistema de CI como en el contenedor Docker?

2021-12-12 17:14 UTC, Asmilex commented
El pull #39 debería solucionar los conflictos.

2021-12-12 18:42 UTC, JAntonioVR commented
Gracias @Asmilex :heart: :tada:

2021-12-12 18:46 UTC, JAntonioVR commented
Listo para revisión @amerigal @paula1999 @Asmilex @JJ

2021-12-12 18:58 UTC, Asmilex reviewed
Lo veo todo perfecto, menos un par de detallicos 👍🏼

2021-12-12 18:58 UTC, Asmilex commented on .circleci/config.yml
> +              python-version: ['3.10-slim', '3.9-slim', '3.8-slim', '3.10', '3.9', '3.8']
He estado leyendo la documentación, pero no veo claro el motivo por el que probar las versiones slim de los contenedores. ¿Por qué se ha tomado esta decisión? En principio, la base del docker solo modifica al propio contenedor, y no a los tests que se ejecuten.

2021-12-12 18:58 UTC, Asmilex commented on .github/workflows/config.yml
> +
¿Por qué se testea solo una versión con Actions, y varias en CircleCI?

2021-12-12 19:03 UTC, JJ requested changes
"Tests" no es un producto mínimamente viable. Todos los PMVs tienen que pasar tests (si no, no son viables). Tendrás que crear un PMV realista cuya viabilidad se compruebe con estos tests.

2021-12-12 19:05 UTC, JJ commented on .github/workflows/config.yml
> +
A ver, eso es razonable. Con que se testee las versiones una vez es suficiente. Lo que no tiene sentido es repetir las mismas versiones aquí y allí, sólo estás tirando créditos de CI.

2021-12-12 19:06 UTC, JAntonioVR commented on .circleci/config.yml
> +              python-version: ['3.10-slim', '3.9-slim', '3.8-slim', '3.10', '3.9', '3.8']
Claro, los test son los mismos, pero se ejecutan en imágenes distintas al tener un contenedor base distinto. Las versiones slim se caracterizan por contener lo mínimo necesario para ejecutar python, que es lo único que necesito antes de instalar las dependencias. Por ello creo que es conveniente utilizarlas en el proyecto. Dejaré esto mismo documentado para evitar dudas de otros revisores.

2021-12-12 19:10 UTC, JAntonioVR commented on .github/workflows/config.yml
> +
De acuerdo a la [lista de comprobación del guión del objetivo 6](http://jj.github.io/IV/documentos/proyecto/6.CI#lista-de-comprobaci%C3%B3n) hay que configurar varios sistemas de integración continua y en uno de ellos testear varias versiones del lenguaje. Yo he testeado las versiones en circleci y he configurado también actions.

2021-12-12 19:37 UTC, amerigal commented on .github/workflows/config.yml
> +
Yo también veo razonable el testeo de una sola versión con las github actions por aquello de que la idea era configurar varios sistemas de integración y en circleci se han testeado más versiones. Lo único es que creo que sería conveniente suprimir el testeo de la versión 3.8-slim en circleci dado que ya se está testeando aquí, por evitar la duplicación de tareas que comenta @JJ.

2021-12-12 19:50 UTC, amerigal requested changes
En general lo veo muy completo, destacando el exhaustivo análisis comparativo con tiempos y tamaños para la elección del contenedor base y la correcta parametrización del contenedor docker para la ejecución de varias versiones.

Solo mencionar la cuestión de la duplicidad de tareas en los CI antes indicada y una pequeña observación en el config de circleci.

2021-12-12 19:50 UTC, amerigal commented on .circleci/config.yml
> +  sample:
Creo preferible utilizar un nombre representativo para el workflow por mayor claridad.

2021-12-12 23:25 UTC, JAntonioVR commented
Listo para revisión @JJ

He eliminado la versión 3.8-slim de  Circle CI y he modificado el milestone M0, que es más apropiado para todo esto.

2021-12-12 23:26 UTC, JAntonioVR commented
Listo para revisión @amerigal 

He solucionado la duplicidad de las versiones y he cambiado el nombre del workflow principal de Circle CI.

2021-12-12 23:26 UTC, JAntonioVR commented
Listo para revisión @Asmilex 

He documentado lo que te he escrito en el comentario, ¿queda suficientemente claro?

2021-12-12 23:43 UTC, amerigal approved these changes
👍

2021-12-13 11:35 UTC, Asmilex commented
> Listo para revisión @Asmilex
> 
> He documentado lo que te he escrito en el comentario, ¿queda suficientemente claro?

Para mí, sigue sin tener sentido utilizar versiones slim y normales. 

Realmente, lo único que te interesa es mirar cuáles de las dos funciona mejor. Una vez lo hayas identificado (que en este caso ha sido la slim), te olvidas de la otra. No te sirve para nada. La idea de este contenedor es proporcionar un entorno de testeo, no un contenedor de Python general. 

Y, por ese motivo, no tiene sentido testear tanto slims como base. Porque una vez instalas tus dependencias, debería funcionar exactamente igual. Me parece redundante pushear dos versiones diferentes. 

(Pero bueno, como hemos hablado antes, el resto está perfecto, así que lo apruebo 👍🏼)

2021-12-13 11:36 UTC, Asmilex approved these changes

2021-12-13 11:54 UTC, paula1999 commented
> > Listo para revisión @Asmilex
> > He documentado lo que te he escrito en el comentario, ¿queda suficientemente claro?
> 
> Para mí, sigue sin tener sentido utilizar versiones slim y normales.
> 
> Realmente, lo único que te interesa es mirar cuáles de las dos funciona mejor. Una vez lo hayas identificado (que en este caso ha sido la slim), te olvidas de la otra. No te sirve para nada. La idea de este contenedor es proporcionar un entorno de testeo, no un contenedor de Python general.
> 
> Y, por ese motivo, no tiene sentido testear tanto slims como base. Porque una vez instalas tus dependencias, debería funcionar exactamente igual. Me parece redundante pushear dos versiones diferentes.
> 
> (Pero bueno, como hemos hablado antes, el resto está perfecto, así que lo apruebo 👍🏼)

Estoy de acuerdo con @Asmilex . En este objetivo se están testeando las diferentes versiones que soporta tu proyecto, por lo que sería redundante testear las versiones `x.y` y `x.y-slim`, pues deberían dar los mismos resultados en los tests.

2021-12-13 17:21 UTC, JAntonioVR commented
Pues me habéis convencido la verdad

2021-12-13 17:30 UTC, JAntonioVR commented
Listo para revisión @paula1999 @Asmilex

2021-12-13 18:00 UTC, Asmilex commented
Por mí todo perfecto :tada:

2021-12-13 18:09 UTC, paula1999 commented
Yo también estoy de acuerdo con los cambios :ok_hand:

2021-12-13 18:10 UTC, paula1999 approved these changes

2021-12-13 18:16 UTC, JAntonioVR commented
Muchas gracias por vuestra ayuda :smile: 

Listo para revisión @JJ

2021-12-15 19:16 UTC, JJ requested changes
Aunque el objetivo en sí está alcanzado, de veras que deberíais darle un poco de más importancia a la justificación de las herramientas elegidas. No has visto qué herramientas hay, y has cogido las dos más comunes. Se trata de que aprendas qué herramientas hay y las elijas. Por favor, haz un pequeño esfuerzo adicional en ese sentido.

2021-12-15 21:00 UTC, JAntonioVR commented
Listo para revisión @JJ

2021-12-16 11:27 UTC, JJ approved these changes
Bueno, por lo menos has buscado otras cosas. Por favor, a partir de ahora los criterios y la búsqueda del panorama debe ir *antes* de la elección.

2021-12-16 11:56 UTC, merged